# Generated by Django 2.0.2 on 2018-04-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_no', models.CharField(max_length=44, verbose_name='学号')),
                ('attend_data', models.DateField(auto_now_add=True, verbose_name='签到日期')),
                ('attend_week', models.CharField(choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五'), (6, '星期六'), (7, '星期日')], max_length=80, verbose_name='星期')),
                ('attend_morning', models.TimeField(verbose_name='签到时间')),
                ('attend_evening', models.TimeField(verbose_name='签到时间')),
                ('absence', models.IntegerField(verbose_name='缺勤时长')),
                ('state', models.CharField(choices=[(0, '异常'), (1, '正常')], default=1, max_length=80, verbose_name='签到状态')),
                ('stu_name', models.CharField(max_length=254, verbose_name='学生姓名1')),
            ],
            options={
                'db_table': 'T_XUPT_ATTEND',
                'ordering': ['-attend_data'],
            },
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_no', models.CharField(max_length=44, verbose_name='学号')),
                ('stu_name', models.CharField(max_length=255, verbose_name='学生姓名')),
                ('class_name', models.CharField(max_length=80, verbose_name='班级')),
                ('late_count', models.IntegerField(default=0, verbose_name='迟到次数')),
                ('absence_count', models.IntegerField(default=0, verbose_name='缺勤次数')),
                ('leave_early', models.IntegerField(default=0, verbose_name='早退次数')),
            ],
            options={
                'db_table': 'T_XUPT_COUNT',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_no', models.CharField(max_length=44, verbose_name='学号')),
                ('stu_name', models.CharField(max_length=255, verbose_name='学生姓名')),
                ('college', models.CharField(max_length=80, verbose_name='学院')),
                ('class_name', models.CharField(max_length=80, verbose_name='班级')),
                ('password', models.CharField(max_length=80, verbose_name='密码')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=80, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('phone', models.CharField(max_length=44, verbose_name='手机号')),
                ('addr', models.CharField(max_length=255, verbose_name='地址')),
                ('date', models.DateField(verbose_name='出生日期')),
            ],
            options={
                'db_table': 'T_XUPT_PERSON',
            },
        ),
    ]
