# Generated by Django 2.0.2 on 2018-04-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='attend_week',
            field=models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday '), (7, 'Sunday')], max_length=80, verbose_name='星期'),
        ),
    ]
