# Generated by Django 2.0.2 on 2018-04-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in_system', '0002_auto_20180418_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='stu_name',
            field=models.CharField(max_length=254, verbose_name='学生姓名'),
        ),
    ]
