# Generated by Django 2.0.2 on 2018-04-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in_system', '0003_auto_20180418_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='attend_morning',
            field=models.TimeField(null=True, verbose_name='签到时间'),
        ),
        migrations.AlterField(
            model_name='attend',
            name='stu_no',
            field=models.CharField(max_length=44, null=True, verbose_name='学号'),
        ),
    ]
