# Generated by Django 2.0.2 on 2018-04-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in_system', '0004_auto_20180418_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='absence',
            field=models.IntegerField(null=True, verbose_name='缺勤时长'),
        ),
        migrations.AlterField(
            model_name='attend',
            name='attend_data',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='签到日期'),
        ),
        migrations.AlterField(
            model_name='attend',
            name='attend_evening',
            field=models.TimeField(null=True, verbose_name='签到时间'),
        ),
        migrations.AlterField(
            model_name='attend',
            name='attend_week',
            field=models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday '), (7, 'Sunday')], max_length=80, null=True, verbose_name='星期'),
        ),
        migrations.AlterField(
            model_name='attend',
            name='state',
            field=models.CharField(choices=[(0, '异常'), (1, '正常')], default=1, max_length=80, null=True, verbose_name='签到状态'),
        ),
        migrations.AlterField(
            model_name='attend',
            name='stu_name',
            field=models.CharField(max_length=254, null=True, verbose_name='学生姓名'),
        ),
    ]
