# Generated by Django 2.0.2 on 2018-04-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in_system', '0005_auto_20180418_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attend',
            options={'ordering': ['-attend_date']},
        ),
        migrations.RenameField(
            model_name='attend',
            old_name='attend_data',
            new_name='attend_date',
        ),
    ]
