# Generated by Django 2.0.2 on 2018-04-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in_system', '0006_auto_20180418_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReAttend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_no', models.CharField(max_length=44, null=True, verbose_name='学号')),
                ('attend_date', models.DateField(auto_now_add=True, null=True, verbose_name='补签日期')),
                ('re_attend_starter', models.CharField(max_length=254, null=True, verbose_name='补签发起人姓名')),
                ('re_attend_eve', models.TimeField(null=True, verbose_name='补签晚打卡')),
                ('re_attend_mor', models.TimeField(null=True, verbose_name='补签早打卡')),
                ('current_handler', models.CharField(max_length=254, null=True, verbose_name='当前处理人')),
                ('re_attend_status', models.CharField(choices=[(1, '处理中'), (2, '通过'), (3, '不通过')], default=1, max_length=80, null=True, verbose_name='补签状态')),
                ('comments', models.CharField(max_length=254, null=True, verbose_name='补签原因')),
            ],
            options={
                'db_table': 'T_XUPT_REATTEND',
            },
        ),
    ]
