# Generated by Django 2.0.2 on 2018-04-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in_system', '0007_reattend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reattend',
            name='attend_date',
            field=models.DateField(null=True, verbose_name='补签日期'),
        ),
        migrations.AlterField(
            model_name='reattend',
            name='re_attend_status',
            field=models.CharField(choices=[(1, '处理中'), (2, '审批通过'), (3, '审批未通过')], default=1, max_length=80, null=True, verbose_name='补签状态'),
        ),
    ]
