# Generated by Django 2.0.2 on 2018-05-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in_system', '0008_auto_20180423_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=80, verbose_name='班级')),
                ('Monday', models.CharField(max_length=80, verbose_name='星期一')),
                ('Tuesday', models.CharField(max_length=80, verbose_name='星期二')),
                ('Wednesday', models.CharField(max_length=80, verbose_name='星期三')),
                ('Thursday', models.CharField(max_length=80, verbose_name='星期四')),
                ('Friday', models.CharField(max_length=80, verbose_name='星期五')),
            ],
            options={
                'db_table': 'T_XUPT_TIMETABLE',
            },
        ),
    ]
