# Generated by Django 2.0.2 on 2018-05-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in_system', '0010_auto_20180516_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attend',
            name='absence',
        ),
        migrations.RemoveField(
            model_name='attend',
            name='attend_evening',
        ),
        migrations.RemoveField(
            model_name='attend',
            name='attend_morning',
        ),
        migrations.AddField(
            model_name='attend',
            name='attend_four',
            field=models.TimeField(null=True, verbose_name='78签到时间'),
        ),
        migrations.AddField(
            model_name='attend',
            name='attend_one',
            field=models.TimeField(null=True, verbose_name='12签到时间'),
        ),
        migrations.AddField(
            model_name='attend',
            name='attend_three',
            field=models.TimeField(null=True, verbose_name='56签到时间'),
        ),
        migrations.AddField(
            model_name='attend',
            name='attend_two',
            field=models.TimeField(null=True, verbose_name='34签到时间'),
        ),
        migrations.AlterField(
            model_name='attend',
            name='state',
            field=models.CharField(choices=[(0, '异常'), (1, '旷课'), (2, '正常')], default=2, max_length=80, null=True, verbose_name='签到状态'),
        ),
    ]
