# Generated by Django 2.0.2 on 2018-05-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in_system', '0011_auto_20180516_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reattend',
            name='re_attend_eve',
        ),
        migrations.RemoveField(
            model_name='reattend',
            name='re_attend_mor',
        ),
        migrations.AlterField(
            model_name='attend',
            name='state',
            field=models.CharField(choices=[(0, '迟到'), (1, '旷课'), (2, '正常'), (3, '已补签')], default=2, max_length=80, null=True, verbose_name='签到状态'),
        ),
    ]
