# Generated by Django 2.0.2 on 2018-05-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in_system', '0012_auto_20180516_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attend',
            old_name='state',
            new_name='state_four',
        ),
        migrations.AddField(
            model_name='attend',
            name='state_one',
            field=models.CharField(choices=[(0, '迟到'), (1, '旷课'), (2, '正常'), (3, '已补签')], default=2, max_length=80, null=True, verbose_name='签到状态'),
        ),
        migrations.AddField(
            model_name='attend',
            name='state_three',
            field=models.CharField(choices=[(0, '迟到'), (1, '旷课'), (2, '正常'), (3, '已补签')], default=2, max_length=80, null=True, verbose_name='签到状态'),
        ),
        migrations.AddField(
            model_name='attend',
            name='state_two',
            field=models.CharField(choices=[(0, '迟到'), (1, '旷课'), (2, '正常'), (3, '已补签')], default=2, max_length=80, null=True, verbose_name='签到状态'),
        ),
    ]
