# Generated by Django 2.0.2 on 2018-05-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in_system', '0013_auto_20180518_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='reattend',
            name='attend_status',
            field=models.CharField(max_length=80, null=True, verbose_name='哪节课，0:12,1:34,2:56,3:78'),
        ),
    ]
