# Generated by Django 2.0.2 on 2018-05-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='自定义设备名字')),
                ('remote', models.CharField(max_length=255, unique=True, verbose_name='自动生成设备名字')),
                ('path', models.CharField(max_length=255, unique=True, verbose_name='设备路径')),
                ('type', models.IntegerField(verbose_name='设备类别')),
                ('key_power', models.BooleanField(verbose_name='开关键')),
                ('key_one', models.BooleanField(verbose_name='1键')),
                ('key_two', models.BooleanField(verbose_name='2键')),
                ('key_three', models.BooleanField(verbose_name='3键')),
                ('key_four', models.BooleanField(verbose_name='4键')),
                ('key_five', models.BooleanField(verbose_name='5键')),
                ('key_six', models.BooleanField(verbose_name='6键')),
                ('key_seven', models.BooleanField(verbose_name='7键')),
                ('key_eight', models.BooleanField(verbose_name='8键')),
                ('key_night', models.BooleanField(verbose_name='9键')),
                ('key_zero', models.BooleanField(verbose_name='0键')),
                ('key_up', models.BooleanField(verbose_name='上键')),
                ('key_down', models.BooleanField(verbose_name='下键')),
                ('key_left', models.BooleanField(verbose_name='左键')),
                ('key_right', models.BooleanField(verbose_name='右键')),
                ('key_ok', models.BooleanField(verbose_name='ok键')),
                ('key_back', models.BooleanField(verbose_name='返回键')),
                ('key_home', models.BooleanField(verbose_name='主页键')),
                ('key_mode', models.BooleanField(verbose_name='空调键')),
                ('key_voice_up', models.BooleanField(verbose_name='音量加键')),
                ('key_voice_down', models.BooleanField(verbose_name='音量减键')),
                ('key_channel_up', models.BooleanField(verbose_name='频道加键')),
                ('key_channel_down', models.BooleanField(verbose_name='频道减键')),
            ],
        ),
    ]
