# Generated by Django 2.0.2 on 2018-05-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remote_control', '0002_device'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='device',
            table='T_XUPT_DEVICE',
        ),
    ]
