# Generated by Django 2.0.2 on 2018-05-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_control', '0003_auto_20180505_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='key_back',
            field=models.BooleanField(default=False, verbose_name='返回键'),
        ),
        migrations.AlterField(
            model_name='device',
            name='key_channel_down',
            field=models.BooleanField(default=False, verbose_name='频道减键'),
        ),
        migrations.AlterField(
            model_name='device',
            name='key_channel_up',
            field=models.BooleanField(default=False, verbose_name='频道加键'),
        ),
        migrations.AlterField(
            model_name='device',
            name='key_down',
            field=models.BooleanField(default=False, verbose_name='下键'),
        ),
        migrations.AlterField(
            model_name='device',
            name='key_eight',
            field=models.BooleanField(default=False, verbose_name='8键'),
        ),
        migrations.AlterField(
            model_name='device',
            name='key_five',
            field=models.BooleanField(default=False, verbose_name='5键'),
        ),
        migrations.AlterField(
            model_name='device',
            name='key_four',
            field=models.BooleanField(default=False, verbose_name='4键'),
        ),
        migrations.AlterField(
            model_name='device',
            name='key_home',
            field=models.BooleanField(default=False, verbose_name='主页键'),
        ),
        migrations.AlterField(
            model_name='device',
            name='key_left',
            field=models.BooleanField(default=False, verbose_name='左键'),
        ),
        migrations.AlterField(
            model_name='device',
            name='key_mode',
            field=models.BooleanField(default=False, verbose_name='空调键'),
        ),
        migrations.AlterField(
            model_name='device',
            name='key_night',
            field=models.BooleanField(default=False, verbose_name='9键'),
        ),
        migrations.AlterField(
            model_name='device',
            name='key_ok',
            field=models.BooleanField(default=False, verbose_name='ok键'),
        ),
        migrations.AlterField(
            model_name='device',
            name='key_one',
            field=models.BooleanField(default=False, verbose_name='1键'),
        ),
        migrations.AlterField(
            model_name='device',
            name='key_power',
            field=models.BooleanField(default=False, verbose_name='开关键'),
        ),
        migrations.AlterField(
            model_name='device',
            name='key_right',
            field=models.BooleanField(default=False, verbose_name='右键'),
        ),
        migrations.AlterField(
            model_name='device',
            name='key_seven',
            field=models.BooleanField(default=False, verbose_name='7键'),
        ),
        migrations.AlterField(
            model_name='device',
            name='key_six',
            field=models.BooleanField(default=False, verbose_name='6键'),
        ),
        migrations.AlterField(
            model_name='device',
            name='key_three',
            field=models.BooleanField(default=False, verbose_name='3键'),
        ),
        migrations.AlterField(
            model_name='device',
            name='key_two',
            field=models.BooleanField(default=False, verbose_name='2键'),
        ),
        migrations.AlterField(
            model_name='device',
            name='key_up',
            field=models.BooleanField(default=False, verbose_name='上键'),
        ),
        migrations.AlterField(
            model_name='device',
            name='key_voice_down',
            field=models.BooleanField(default=False, verbose_name='音量减键'),
        ),
        migrations.AlterField(
            model_name='device',
            name='key_voice_up',
            field=models.BooleanField(default=False, verbose_name='音量加键'),
        ),
        migrations.AlterField(
            model_name='device',
            name='key_zero',
            field=models.BooleanField(default=False, verbose_name='0键'),
        ),
    ]
