# Generated by Django 2.0.2 on 2018-05-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remote_control', '0004_auto_20180505_0220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='key_power',
            new_name='KEY_1',
        ),
    ]
