# Generated by Django 2.0.2 on 2018-05-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_control', '0007_auto_20180505_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='create_time',
            field=models.DateTimeField(auto_created=True, null=True, verbose_name='设备创建时间'),
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.IntegerField(null=True, verbose_name='是否已完成命名，0没有，1完成'),
        ),
    ]
