# Generated by Django 2.0.2 on 2018-05-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_control', '0008_auto_20180505_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='create_time',
            field=models.CharField(max_length=255, null=True, verbose_name='设备创建时间'),
        ),
    ]
