# Generated by Django 2.0.2 on 2018-05-05 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remote_control', '0010_device_air_conditioner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='type',
        ),
    ]
