# Generated by Django 2.0.2 on 2018-05-13 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remote_control', '0012_remove_device_air_conditioner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='key_night',
            new_name='key_nine',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='key_voice_down',
            new_name='key_volume_down',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='key_voice_up',
            new_name='key_volume_up',
        ),
    ]
